// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiAplicacion.Models;

namespace AFFMUSA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190609035821_Implementation")]
    partial class Implementation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AFFMUSA.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AllowBilling");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Company_Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Contact_Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int>("Ext")
                        .HasMaxLength(5);

                    b.Property<string>("Fax");

                    b.Property<string>("Job_Title")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Notes");

                    b.Property<string>("Phone");

                    b.Property<string>("Photo");

                    b.Property<int>("ZipCode");

                    b.HasKey("ClientID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("AFFMUSA.Models.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientID");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("CountryID");

                    b.HasIndex("ClientID");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("AFFMUSA.Models.Lists.States", b =>
                {
                    b.Property<int>("StatesID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientID");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("StatesID");

                    b.HasIndex("ClientID");

                    b.ToTable("States");
                });

            modelBuilder.Entity("AFFMUSA.Models.Country", b =>
                {
                    b.HasOne("AFFMUSA.Models.Client")
                        .WithMany("Countries")
                        .HasForeignKey("ClientID");
                });

            modelBuilder.Entity("AFFMUSA.Models.Lists.States", b =>
                {
                    b.HasOne("AFFMUSA.Models.Client")
                        .WithMany("States")
                        .HasForeignKey("ClientID");
                });
#pragma warning restore 612, 618
        }
    }
}
